/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dangky;

import DangNhap.DangNhapChinh;
import KetNoiSQL.KetNoi;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.Vector;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.ButtonModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.w3c.dom.css.RGBColor;

/**
 *
 * @author Minh Huan
 */
public class LoginFrame extends javax.swing.JFrame {

    /**
     * Creates new form LoginFrame
     */
    
    
    public LoginFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        jPanel_LoginFrame.setVisible(true);
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel_LoginFrame = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField_ID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton_Login = new javax.swing.JButton();
        jLabel_Sigin = new javax.swing.JLabel();
        Jlabel_Main_Note = new javax.swing.JLabel();
        jLabel_Note_MSV = new javax.swing.JLabel();
        Jlabel_Note_MK = new javax.swing.JLabel();
        jPasswordField_Pass = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Roboto Medium", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("ĐĂNG NHẬP");

        jLabel5.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 102));
        jLabel5.setText("Sinh viên");

        jLabel2.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel2.setText("Tên đăng nhập");

        jTextField_ID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_IDFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_IDFocusLost(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel3.setText("Mật khẩu");

        jLabel4.setBackground(new java.awt.Color(102, 102, 102));
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Quên mật khẩu ?");

        jButton_Login.setBackground(new java.awt.Color(51, 102, 255));
        jButton_Login.setFont(new java.awt.Font("Roboto Black", 1, 13)); // NOI18N
        jButton_Login.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Login.setText("ĐĂNG NHẬP");
        jButton_Login.setBorder(null);
        jButton_Login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_LoginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_LoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_LoginMouseExited(evt);
            }
        });

        jLabel_Sigin.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel_Sigin.setText("Đăng ký");
        jLabel_Sigin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Sigin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_SiginMouseClicked(evt);
            }
        });

        Jlabel_Main_Note.setFont(new java.awt.Font("sansserif", 2, 12)); // NOI18N
        Jlabel_Main_Note.setForeground(new java.awt.Color(204, 0, 0));

        jLabel_Note_MSV.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel_Note_MSV.setForeground(new java.awt.Color(204, 0, 0));

        Jlabel_Note_MK.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        Jlabel_Note_MK.setForeground(new java.awt.Color(204, 0, 0));

        jPasswordField_Pass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField_PassFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordField_PassFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel_LoginFrameLayout = new javax.swing.GroupLayout(jPanel_LoginFrame);
        jPanel_LoginFrame.setLayout(jPanel_LoginFrameLayout);
        jPanel_LoginFrameLayout.setHorizontalGroup(
            jPanel_LoginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_LoginFrameLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel_LoginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPasswordField_Pass, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel_LoginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_LoginFrameLayout.createSequentialGroup()
                            .addComponent(jButton_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel_LoginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel_Sigin, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addComponent(Jlabel_Main_Note, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                        .addGroup(jPanel_LoginFrameLayout.createSequentialGroup()
                            .addGroup(jPanel_LoginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel_LoginFrameLayout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel_Note_MSV, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel_LoginFrameLayout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Jlabel_Note_MK, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addComponent(jTextField_ID, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel_LoginFrameLayout.setVerticalGroup(
            jPanel_LoginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_LoginFrameLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel_LoginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel_Note_MSV, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_LoginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Jlabel_Note_MK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jPasswordField_Pass, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Jlabel_Main_Note, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanel_LoginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel_LoginFrameLayout.createSequentialGroup()
                        .addComponent(jLabel_Sigin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jLabel6.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 0, 0));
        jLabel6.setText("Quay lại");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel_LoginFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(0, 0, 0)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel_LoginFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_LoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_LoginMouseClicked
        // TODO add your handling code here:
        
        String id = jTextField_ID.getText();
        id = id.toUpperCase();
        id = id.trim();
        String pass = jPasswordField_Pass.getText();
        boolean checkLogin = true;
        if("".equals(id)) {
            jLabel_Note_MSV.setText("(*)");
            checkLogin = false;
        }
        if("".equals(pass)) {
            Jlabel_Note_MK.setText("(*)");
            checkLogin = false;
        }
        
        
        
        
        
        
        if(checkLogin) {

            System.out.println("id" + id + "pass: "+ pass);
            Connection ketNoi = (Connection) KetNoi.ConnectSQL();
            
            String sql = "select * from TAIKHOAN where TENDANGNHAP = ? and MATKHAU = ? and LOAITK = N'SINHVIEN'";
            try {
                
                PreparedStatement ps = ketNoi.prepareStatement(sql);
                ps.setString(1, id);
                ps.setString(2, pass);
                ResultSet rs = ps.executeQuery();
                if(rs.next()){
                    String matk = rs.getString("MATK");
                    String sql1 = "select MASV from SINHVIEN where MATK = ?";
                    PreparedStatement ps1 = ketNoi.prepareStatement(sql1);
                    ps1.setString(1, matk);
                    ResultSet rs1 = ps1.executeQuery();
                    if(rs1.next()){
                        String masv = rs1.getString("MASV");
                        new MainFrame(masv).setVisible(true);
                        this.setVisible(false);
                    }
                }
                else{
                    Jlabel_Main_Note.setText("Mã tài khoản hoặc mật khẩu không đúng");
                }
            } catch (SQLException e) {
                printStackTrace();
            }
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
//            String sql = "select * from sinhvien where MASV = ?";
//            try {
//               PreparedStatement ps = ketNoi.prepareStatement(sql);
//               ps.setString(1, id);
//               ResultSet rs = ps.executeQuery();
//               if(rs.next() ){
//                   //khong tim thay msv
//                   //co ma svi
//                   String maTK = rs.getString("MATK");
//                   System.out.println("matk: "+ maTK);
//                   if(maTK == null) {
//                        Jlabel_Main_Note.setText("*MSV chưa đăng ký tài khoản");
//                   }
//                   else {
//                        String sql2 = "select * from TAIKHOAN where MATK = ? and MATKHAU = ?";
//                        PreparedStatement ps1 = ketNoi.prepareStatement(sql2);
//                        ps1.setString(1, maTK);
//                        ps1.setString(2, pass);
//                        ResultSet rs2 = ps1.executeQuery();
//                        if(rs2.next()){
//                            new MainFrame(id).setVisible(true);
//                            this.setVisible(false);
//                        }
//                        else {
//                            Jlabel_Main_Note.setText("*Sai mật khẩu");
//                        }
//                          
//                   }
//                   
//               }
//               else {
//                   Jlabel_Main_Note.setText("*Sai MSV hoặc mật khẩu");
//                   return;
//               }
//            } catch (Exception e) {
//                System.out.println("error...");
//                e.getStackTrace();
//            }
//            
            
            
            
            
        }
        
        
        
    }//GEN-LAST:event_jButton_LoginMouseClicked

    private void jTextField_IDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_IDFocusGained
        // TODO add your handling code here:
        
        Jlabel_Main_Note.setText("");
        jTextField_ID.setBackground(Color.WHITE);
        
    }//GEN-LAST:event_jTextField_IDFocusGained

    private void jButton_LoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_LoginMouseEntered
        // TODO add your handling code here:
        jButton_Login.setBackground(Color.BLUE);
    }//GEN-LAST:event_jButton_LoginMouseEntered

    private void jButton_LoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_LoginMouseExited
        // TODO add your handling code here:
        jButton_Login.setBackground(new Color(51,102,225));
    }//GEN-LAST:event_jButton_LoginMouseExited

    private void jTextField_IDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_IDFocusLost
        // TODO add your handling code here:
        String id = jTextField_ID.getText();
        System.out.println("id: " +id);
        if("".equals(id)){
            jTextField_ID.setBackground(new Color(181, 208, 255));
        }
    }//GEN-LAST:event_jTextField_IDFocusLost

    private void jPasswordField_PassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField_PassFocusGained
        // TODO add your handling code here:
        Jlabel_Main_Note.setText("");
        jPasswordField_Pass.setBackground(Color.WHITE);
    }//GEN-LAST:event_jPasswordField_PassFocusGained

    private void jPasswordField_PassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField_PassFocusLost
        // TODO add your handling code here:
        String id = jTextField_ID.getText();
        System.out.println("id: " +id);
        if("".equals(id)){
            jPasswordField_Pass.setBackground(new Color(181, 208, 255));
        }
    }//GEN-LAST:event_jPasswordField_PassFocusLost

    private void jLabel_SiginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_SiginMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new SiginFrame().setVisible(true);
    }//GEN-LAST:event_jLabel_SiginMouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new DangNhapChinh().setVisible(true);
    }//GEN-LAST:event_jLabel6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Jlabel_Main_Note;
    private javax.swing.JLabel Jlabel_Note_MK;
    private javax.swing.JButton jButton_Login;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel_Note_MSV;
    private javax.swing.JLabel jLabel_Sigin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_LoginFrame;
    private javax.swing.JPasswordField jPasswordField_Pass;
    private javax.swing.JTextField jTextField_ID;
    // End of variables declaration//GEN-END:variables

    private void printStackTrace() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
