/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dangky;
import java.sql.ResultSet;
import KetNoiSQL.KetNoi;
import com.sun.jdi.connect.spi.Connection;
import javax.swing.JOptionPane;
import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.PreparedStatement;
import java.awt.event.KeyListener;
import java.sql.CallableStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Minh Huan
 */
public class SiginFrame extends javax.swing.JFrame {

    /**
     * Creates new form SigninFrame
     */
    java.sql.Connection ketNoi = (java.sql.Connection) KetNoi.ConnectSQL();
    private String masvDK,hotenDK, lopDK, sdtDK;
    private  boolean tonTaiThongTinSV = false;
    @Override
    public void layout() {
        super.layout(); //To change body of generated methods, choose Tools | Templates.
    }
    public SiginFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog_DangKyTK = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField_TenDangNhap = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPassword_MatKhau = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        jPassword_MatKhauLai = new javax.swing.JPasswordField();
        jButton_DangKy = new javax.swing.JButton();
        jLabel_QuayLai = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel_NoteMatKhau = new javax.swing.JLabel();
        jLabel_NoteTDN = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTextField_MaSV_SK = new javax.swing.JTextField();
        jButton_TiepTuc = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField_HoTenSV_DK = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField_LopSV_DK = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField_SDTSV_DK = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel_NotePass = new javax.swing.JLabel();
        jLabel_NoteSDT = new javax.swing.JLabel();

        jDialog_DangKyTK.setMinimumSize(new java.awt.Dimension(345, 430));
        jDialog_DangKyTK.setModal(true);
        jDialog_DangKyTK.setPreferredSize(new java.awt.Dimension(345, 430));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel4.setText("Tên đăng nhập");

        jTextField_TenDangNhap.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_TenDangNhapKeyReleased(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel7.setText("Mật khẩu");

        jLabel8.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel8.setText("Nhập lại mật khẩu");

        jPassword_MatKhauLai.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPassword_MatKhauLaiFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPassword_MatKhauLaiFocusLost(evt);
            }
        });

        jButton_DangKy.setText("ĐĂNG KÝ");
        jButton_DangKy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DangKyActionPerformed(evt);
            }
        });

        jLabel_QuayLai.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel_QuayLai.setText("Quay lại");
        jLabel_QuayLai.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_QuayLai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_QuayLaiMouseClicked(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 102));
        jLabel12.setText("ĐĂNG KÝ ");

        jPanel4.setBackground(new java.awt.Color(0, 0, 102));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel_QuayLai, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                        .addComponent(jButton_DangKy, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPassword_MatKhauLai)
                    .addComponent(jPassword_MatKhau)
                    .addComponent(jTextField_TenDangNhap)
                    .addComponent(jLabel_NoteMatKhau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_NoteTDN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_TenDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_NoteTDN, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(12, 12, 12)
                .addComponent(jPassword_MatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPassword_MatKhauLai, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_NoteMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel_QuayLai)
                        .addGap(6, 6, 6))
                    .addComponent(jButton_DangKy, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialog_DangKyTKLayout = new javax.swing.GroupLayout(jDialog_DangKyTK.getContentPane());
        jDialog_DangKyTK.getContentPane().setLayout(jDialog_DangKyTKLayout);
        jDialog_DangKyTKLayout.setHorizontalGroup(
            jDialog_DangKyTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDialog_DangKyTKLayout.setVerticalGroup(
            jDialog_DangKyTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Roboto Medium", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("THÔNG TIN");

        jTextField_MaSV_SK.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_MaSV_SKFocusGained(evt);
            }
        });

        jButton_TiepTuc.setBackground(new java.awt.Color(51, 102, 255));
        jButton_TiepTuc.setFont(new java.awt.Font("Roboto Black", 1, 13)); // NOI18N
        jButton_TiepTuc.setForeground(new java.awt.Color(255, 255, 255));
        jButton_TiepTuc.setText("TIẾP TỤC");
        jButton_TiepTuc.setBorder(null);
        jButton_TiepTuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_TiepTucActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel5.setText("Đăng nhập");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel2.setText("Mã sinh viên (*)");

        jTextField_HoTenSV_DK.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_HoTenSV_DKFocusGained(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel6.setText("Họ và tên (*)");

        jLabel9.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel9.setText("Lớp (*)");

        jTextField_LopSV_DK.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_LopSV_DKFocusGained(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel10.setText("Số điện thoại (*)");

        jTextField_SDTSV_DK.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_SDTSV_DKFocusGained(evt);
            }
        });
        jTextField_SDTSV_DK.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_SDTSV_DKKeyReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("sansserif", 2, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("*Các trường có (*) là bắt buộc");

        jLabel_NotePass.setFont(new java.awt.Font("sansserif", 2, 12)); // NOI18N
        jLabel_NotePass.setForeground(new java.awt.Color(255, 0, 0));

        jLabel_NoteSDT.setForeground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_TiepTuc, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_SDTSV_DK, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_LopSV_DK, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextField_MaSV_SK, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                                .addComponent(jTextField_HoTenSV_DK)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel_NoteSDT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap(18, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_NotePass, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(21, 21, 21))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_MaSV_SK, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_HoTenSV_DK, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField_LopSV_DK, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_NoteSDT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField_SDTSV_DK, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jLabel_NotePass, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_TiepTuc, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private PreparedStatement ketNoiSql(String sql) throws SQLException{
        PreparedStatement ps = ketNoi.prepareStatement(sql);
        return ps;
    }
    
    private String taoMaTaiKhoan(String loaiTK){
        String sql = "select MAX(RIGHT(MATK, 3)) as maxid from TAIKHOAN where LEFT(MATK, 4) = N'"+loaiTK+"'";
        String  maTK= loaiTK;
        try {
            PreparedStatement ps = ketNoi.prepareStatement(sql);
            ResultSet rs= ps.executeQuery();
            if(rs.next()){
                String a = rs.getString("maxid");
                int b = Integer.parseInt(a);
                b = b+1;
                if(b<=9) maTK = maTK + "00"+b;
                if(b<=99 && b>9) maTK = maTK + "0"+b;
                if(b>99) maTK = maTK +b;
            }
            
        } catch (NumberFormatException | SQLException e) {
        }
        return  maTK;
    }
    private void jButton_TiepTucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_TiepTucActionPerformed
        // Dang ky tai khoan:
        String masv = jTextField_MaSV_SK.getText();
        masv = masv.toUpperCase();
        String hoten = jTextField_HoTenSV_DK.getText();
        String lop = jTextField_LopSV_DK.getText();
        String sdt = jTextField_SDTSV_DK.getText();
        boolean check = true;
        if(masv.equals("")){
            jTextField_MaSV_SK.setBackground(new Color(181, 208, 255));
            check = false;
        }
        if(hoten.equals("")){
            jTextField_HoTenSV_DK.setBackground(new Color(181, 208, 255));
            check = false;
        }
        if(lop.equals("")){
            jTextField_LopSV_DK.setBackground(new Color(181, 208, 255));
            check = false;
        }
        if(sdt.equals("")){
            
            jTextField_SDTSV_DK.setBackground(new Color(181, 208, 255));
            check = false;
        }     
        else {
                if(sdt.length() != 10){
                jLabel_NoteSDT.setText("Số điện thoại không phù hợp");
                check = false;
                }
        }
        
        if(check){
            masvDK = masv;
            hotenDK = hoten;
            lopDK = lop;
            sdtDK = sdt;
//            this.setVisible(false);
             String sql = "select * from SINHVIEN where MASV = N'"+masvDK+"'";
             try {
                ResultSet rs = ketNoiSql(sql).executeQuery();
                if(rs.next()){
                    String matksan = rs.getString("MATK");
                    if(matksan==null){
                        tonTaiThongTinSV = true;
                    }
                    else{
                        JOptionPane.showMessageDialog(rootPane, "Sinh viên đã đăng ký tài khoản");
                        return;
                    }
                    
                }
                else {
                    tonTaiThongTinSV = false;
                    this.setVisible(false);
                    jDialog_DangKyTK.setLocationRelativeTo(null);
                    jDialog_DangKyTK.setVisible(true);
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }


            
        }

        
        
        
    }//GEN-LAST:event_jButton_TiepTucActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new LoginFrame().setVisible(true);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jTextField_SDTSV_DKKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_SDTSV_DKKeyReleased
        // TODO add your handling code here:
        String sdt = jTextField_SDTSV_DK.getText();
        if(sdt.isEmpty()) {
            jButton_TiepTuc.setEnabled(true);
            return;
        }
        try {
            int a = Integer.parseInt(sdt);
            jLabel_NoteSDT.setText("");
            jButton_TiepTuc.setEnabled(true);
            
        } catch (Exception e) {
            jLabel_NoteSDT.setText("Số điện thoại chỉ chứa các số");
            jButton_TiepTuc.setEnabled(false);
        }
        
        
    }//GEN-LAST:event_jTextField_SDTSV_DKKeyReleased

    private void jTextField_MaSV_SKFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_MaSV_SKFocusGained
        // TODO add your handling code here:
        jTextField_MaSV_SK.setBackground(Color.WHITE);
    }//GEN-LAST:event_jTextField_MaSV_SKFocusGained

    private void jTextField_HoTenSV_DKFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_HoTenSV_DKFocusGained
        // TODO add your handling code here:
        jTextField_HoTenSV_DK.setBackground(Color.WHITE);
    }//GEN-LAST:event_jTextField_HoTenSV_DKFocusGained

    private void jTextField_LopSV_DKFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_LopSV_DKFocusGained
        // TODO add your handling code here:
        jTextField_LopSV_DK.setBackground(Color.WHITE);
        
    }//GEN-LAST:event_jTextField_LopSV_DKFocusGained

    private void jTextField_SDTSV_DKFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_SDTSV_DKFocusGained
        // TODO add your handling code here:
        jTextField_SDTSV_DK.setBackground(Color.WHITE);
    }//GEN-LAST:event_jTextField_SDTSV_DKFocusGained

    private void jLabel_QuayLaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_QuayLaiMouseClicked
        // TODO add your handling code here:
        jDialog_DangKyTK.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_jLabel_QuayLaiMouseClicked

    private void jButton_DangKyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DangKyActionPerformed
        // TODO add your handling code here:
        
        String tenDangNhap = jTextField_TenDangNhap.getText();
        String matKhau = jPassword_MatKhau.getText();
        String matKhauLai = jPassword_MatKhauLai.getText();
        
        boolean check = true;
        
        if(tenDangNhap.equals("")){
            check = false;
        }
        if(matKhau.equals("")){
            check = false;
        }
        if(matKhau.equals("")){
            check = false;
        }
        
        
        
        
        if(check){
            if(matKhau.equals(matKhauLai)){
               if(tonTaiThongTinSV){
                   String sqlMaTK = "select dbo.AUTO_MATK() as MATK";
                    String matk = "";
                    try {
                        PreparedStatement ps = ketNoi.prepareStatement(sqlMaTK);
                        ResultSet rs = ps.executeQuery();
                        if(rs.next()){
                            matk = rs.getString("MATK");
                            System.out.println("MATK = " + matk);
                        }
                    } catch (SQLException e) {
                        e.printStackTrace();
                    }

                    String sqlThemTK = "{Call Sp_ThemTaiKhoan(?, ?, ?)}";
                    try {
                        CallableStatement ps = ketNoi.prepareCall(sqlThemTK);
                        ps.setString(1, tenDangNhap);
                        ps.setString(2, matKhau);
                        ps.setString(3, "SINHVIEN");
                        ps.executeUpdate();
                        System.out.println("Them tk thanh cong");

                    } catch (SQLException e) {
                        System.out.println("Them tk khong thanh cong");
                    }
                            
                    
                   String sql2 = "update SINHVIEN set MATK = '"+matk+"' where MASV = '"+masvDK+"'";
                   try {
                       ketNoiSql(sql2).executeUpdate();
                   } catch (SQLException ex) {
                       Logger.getLogger(SiginFrame.class.getName()).log(Level.SEVERE, null, ex);
                   }
                   jDialog_DangKyTK.setVisible(false);
                   new LoginFrame().setVisible(true);
                   JOptionPane.showMessageDialog(rootPane, "Tạo tài khoản thành công");
               }
               else{
                   String sqlMaTK = "select dbo.AUTO_MATK() as MATK";
                    String matk = "";
                    try {
                        PreparedStatement ps = ketNoi.prepareStatement(sqlMaTK);
                        ResultSet rs = ps.executeQuery();
                        if(rs.next()){
                            matk = rs.getString("MATK");
                            System.out.println("MATK = " + matk);
                        }
                    } catch (SQLException e) {
                        e.printStackTrace();
                    }

                    String sqlThemTK = "{Call Sp_ThemTaiKhoan(?, ?, ?)}";
                    try {
                        CallableStatement ps = ketNoi.prepareCall(sqlThemTK);
                        ps.setString(1, tenDangNhap);
                        ps.setString(2, matKhau);
                        ps.setString(3, "SINHVIEN");
                        ps.executeUpdate();
                        System.out.println("Them tk thanh cong");

                    } catch (SQLException e) {
                        System.out.println("Them tk khong thanh cong");
                    }
                            
                        String sql2 = "insert into SINHVIEN(MASV, HOTEN, LOP, SDT, MATK) values(?, ?, ?, ?, ?)";
                        try {
                            PreparedStatement ps1 = ketNoi.prepareStatement(sql2);
                             ps1.setString(1, masvDK);
                             ps1.setString(2, hotenDK);
                             ps1.setString(3, lopDK);
                             ps1.setString(4, sdtDK);
                             ps1.setString(5, matk);
                             ps1.executeUpdate();
                        } catch (Exception e) {
                            e.printStackTrace();
                        }
                       
                        
                       
                        jDialog_DangKyTK.setVisible(false);
                        new LoginFrame().setVisible(true);
                        JOptionPane.showMessageDialog(rootPane, "Tạo tài khoản thành công");
               }
            }
            else {
                JOptionPane.showMessageDialog(rootPane, "Mật khẩu không trùng khớp");
            }
        }
        else {
            JOptionPane.showMessageDialog(rootPane, "Các trường trên là bắt buộc");
        }
        
    }//GEN-LAST:event_jButton_DangKyActionPerformed

    private void jPassword_MatKhauLaiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPassword_MatKhauLaiFocusLost
        // TODO add your handling code here:
        String matKhau = jPassword_MatKhau.getText();
        String matKhauLai = jPassword_MatKhauLai.getText();
        if(!matKhau.equals(matKhauLai)){
             jLabel_NoteMatKhau.setText("Mật khẩu không trùng khớp");
        }
    }//GEN-LAST:event_jPassword_MatKhauLaiFocusLost

    private void jPassword_MatKhauLaiFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPassword_MatKhauLaiFocusGained
        // TODO add your handling code here:
        jLabel_NoteMatKhau.setText("");
    }//GEN-LAST:event_jPassword_MatKhauLaiFocusGained

    private void jTextField_TenDangNhapKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_TenDangNhapKeyReleased
        // TODO add your handling code here:
        String tenDangNhap = jTextField_TenDangNhap.getText();
        if(tenDangNhap.equals("")){
            jLabel_NoteTDN.setText("");
            return;
        }
        
        String sql = "select * from TAIKHOAN where TENDANGNHAP = ?";
            try {
                PreparedStatement ps = ketNoi.prepareStatement(sql);
                ps.setString(1, tenDangNhap);
                ResultSet rs = ps.executeQuery();
                
                if(rs.next()){
                    jLabel_NoteTDN.setForeground(new Color(252, 68, 35));
                    jLabel_NoteTDN.setText("Tên đăng nhập đã tồn tại");
                    
                }
                else {
                    jLabel_NoteTDN.setText("Tên đăng nhập có sẵn");
                    jLabel_NoteTDN.setForeground(new Color(65, 242, 104));
                }
            } catch (Exception e) {
            }
    }//GEN-LAST:event_jTextField_TenDangNhapKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SiginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SiginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SiginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SiginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SiginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_DangKy;
    private javax.swing.JButton jButton_TiepTuc;
    private javax.swing.JDialog jDialog_DangKyTK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_NoteMatKhau;
    private javax.swing.JLabel jLabel_NotePass;
    private javax.swing.JLabel jLabel_NoteSDT;
    private javax.swing.JLabel jLabel_NoteTDN;
    private javax.swing.JLabel jLabel_QuayLai;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPasswordField jPassword_MatKhau;
    private javax.swing.JPasswordField jPassword_MatKhauLai;
    private javax.swing.JTextField jTextField_HoTenSV_DK;
    private javax.swing.JTextField jTextField_LopSV_DK;
    private javax.swing.JTextField jTextField_MaSV_SK;
    private javax.swing.JTextField jTextField_SDTSV_DK;
    private javax.swing.JTextField jTextField_TenDangNhap;
    // End of variables declaration//GEN-END:variables
}
